### ISSUE TITLE
wrong global best solution is stored

### ISSUE THREAD

**Issue by MarcusCramer91** [jakobbossek/cmaesr#14]
arx is used instead of arx.repaired to store the new best solution vector, which leads to wrong x values

**Comment by jakobbossek** [comment]
We are just *penalizing infeasible solution*, but not forcing them to stick to the bounds. This is no error. See the CMA tutorial for details: *"The repaired solution is disregarded afterwards."*

**Comment by jakobbossek** [comment]
We discussed that via e-mail. Update of the best so far solution is done only based on the non-penalized individuals. Thus, the corresponding columns in `arx` and `arx.repaired` respectively are equal. Closing.
