### ISSUE TITLE
Covmat can contain Inf, NA, NaN values

### ISSUE THREAD

**Issue by MarcusCramer91** [jakobbossek/cmaesr#16]
When using cmaesr with default stopping conditions as restart criteria (and maxeval as ultimate stopping criterion), the following error might appear (see attachment). This can happen when the covariance matrix contains Inf, NA or NaN values.

![bug](https://cloud.githubusercontent.com/assets/7646847/12002243/f6c3d048-aaf9-11e5-8fd2-c2a6c1c48136.png)

**Comment by MarcusCramer91** [comment]
apparently eigenvalues can become negative in the stopping condition stopOnNoEffectAxis because this while this is caught in indefCovMat the other stopping conditions are still checked

**Comment by jakobbossek** [comment]
Ok, I guess we should do the following:
* *unexport* the `indefCovMat` stopping condition
* always append `indefCovMat` as the first stopping condition internally
* Maybe not check all stopping conditions. Instead check them iteratively until the first one is met.

What do you think?

**Comment by MarcusCramer91** [comment]
Sounds good

**Comment by jakobbossek** [comment]
Done
